version: '3.8'

services:
    web:
      build: .
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - 8000:8000
      depends_on:
        - db
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        interval: 30s
        timeout: 10s
        retries: 5
      restart: always

    db:
      image: postgres:16.3
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: bookdb
        POSTGRES_USER: bookuser
        POSTGRES_PASSWORD: djbooks@6307
      ports:
       - 5433:5432

volumes:
  postgres_data: